### ISSUE TITLE
QuadrigaCX ticker and API trading

### ISSUE THREAD

**Issue by daldwinc** [lamassu/lamassu-server#108]
QuadrigaCX (https://www.quadrigacx.com/) is a popular Canadian exchange, with a high volume for CAD trading pairs.

This enhancement request is two part:

1. Implement the option of using the QuadrigaCX ticker as spot price source

2. Implement auto-rebuy functionality for QuadrigaCX

Their API documentation can be found here: https://www.quadrigacx.com/api_info

Cheers,
Dave

**Comment by naconner** [comment]
This is probably our next-most requested exchange for support.

When we turn towards expanding ticker/trader options (sometime after new AML/KYC features), I'd say QuadrigaCX is at the top followed by BTCMarkets (AUD).

**Comment by naconner** [comment]
QuadrigaCX support is now slated for the third release (_Defiant Dingirma_) after v7, which is currently being finalised.
