### ISSUE TITLE
crypto_atoms bigint does not allow payments over ~9.2ETH

### ISSUE THREAD

**Issue by DanielWeigl** [lamassu/lamassu-server#115]
At the DB layer `crypto_atoms`  is stored as  `bigint`, but according to [the postgres docu](https://www.postgresql.org/docs/9.1/static/datatype-numeric.html) the max value is 9223372036854775807 which equals 9.2 ETH. Transactions over this value fail and get stuck.

Eg. see here:
https://github.com/lamassu/lamassu-server/blob/2df4b4e195df85e52c201eb9f7aa40fab8cbef06/migrations/011-transactions-reload-2.js#L16

**Comment by joshmh** [comment]
Good catch. How's this?

https://github.com/lamassu/lamassu-server/pull/116

**Comment by joshmh** [comment]
Yeah, everything has always been converted to BN once it's loaded from the db, so it should work the same. Still have to test it.
