### ISSUE TITLE
Test trader with different currency than locale

### ISSUE THREAD

**Issue by joshmh** [lamassu/lamassu-server#12]
Test with Bitstamp (USD) trading for a machine set to ILS. The Bitcoin Machine should go out of bitcoins when there is less than one ILS worth of currency in Bitstamp, not when there is less than one USD in Bitstamp. Make the wallet balance much higher, because lamassu-server selects the lowest of wallet balance and trader balance.

**Note**: This can only be done once the latest code is deployed to a new server.

**Comment by naconner** [comment]
No longer relevant with v3.
