### ISSUE TITLE
Send notification emails to operators

### ISSUE THREAD

**Issue by joshmh** [lamassu/lamassu-server#32]
Operators really want to know the following:
- If one of their machines is down. E.g., lamassu-server hasn't received a poll request in 5 minutes.
- They are low, or out of bitcoins.
- A 3rd party service is down (e.g., blockchain.info, bitcoinaverage).

lamassu-server should send the operator an email detailing the issue. It should be careful not to continue sending emails for the same problem, so if a machine is down for 30 minutes, it shouldn't send an email every 5 minutes.

**Comment by naconner** [comment]
Accomplished in current alpha. :+1: To close.

**Comment by naconner** [comment]
Now a feature in v3.
