### ISSUE TITLE
Make ssu-commission specific to all devices (machines)

### ISSUE THREAD

**Issue by richardsj** [lamassu/lamassu-server#65]
ssu-commission is a quick and convenient, scriptable way to adjust commission but it appears to be global to a server.

As a result of this, there's a tendency to run multiple servers, all with different transaction histories and so on.  Worse than this the transaction table -> ID is not an integer, not a UUID so merging them is not a trivial feat (to see what sales were like over a given period for example).

Suggestion: ssu-commission should be [global] or [device-name] and/or take the values as parameters on the CLI
With no parameters it should output the values

**Comment by naconner** [comment]
Thanks for the suggestion. We have this implemented directly into the admin in the alpha version:

https://github.com/lamassu/lamassu-install/tree/nextgen#lamassu-install

**Comment by naconner** [comment]
Individual machine commission settings in v3. Closing.
