### ISSUE TITLE
lamassu-disable-trading doesn't have a counterpart (reverse)

### ISSUE THREAD

**Issue by richardsj** [lamassu/lamassu-server#66]
The command to disable trading is useful but needs to have the ability to re-enable (the last used values ideally) and/or set new tokens on the CLI - e.g. if a script decides to switch to use a different hedging source.

This opens the way to automating a lot of useful heuristics for determining when the hedge, how much, and from where.  A future incarnation might involve cross-currency hedging (if other cryptos become a real thing)

**Comment by naconner** [comment]
As I understand, lamassu-disable-trading removes these values, so they're no longer held in the database to renable.

Most ticker/traders have a setup script: https://github.com/lamassu/lamassu-bitstamp/blob/master/setup

Or you could run lamassu-update-config on a .json file that holds the db tokens.

Regarding more dynamic hedging, that's a good idea to explore. Would welcome further thoughts.

**Comment by richardsj** [comment]
Nice - in that case I'd suggest creating a symlink for that script to `ssu-enable-trading-bitstamp` for now, just for simplicity so it's in the `$PATH`

**Comment by naconner** [comment]
Closing. Handled well in v3.
